# site settings
title: Azure
subtitle: To Kobe Bryant
email: imat24@outlook.com
description: Once Upon A Time in Los Angels
baseurl: /24 # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Sean
street_address: 8&24 LA
city: Shenzhen
state: Guangzhou
zip_code: 518000
country: China
phone: (+86) 13713972908

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 15

# social settings
500px_url:
facebook_url:
github_url: https://github.com/i-mat
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
